<#
  gen_seed_sql.ps1

  Reads literature/*.md, notes/*.md and the article cards in
  literature.html / directory.html, then generates
  supabase/migrations/0003_seed_articles.sql
  (no runtime needed; paste it into the Supabase SQL Editor to import
  the existing articles).

  Usage (from the temp-pages folder):
    powershell -ExecutionPolicy Bypass -File tools/gen_seed_sql.ps1

  The generated SQL upserts on (section, slug) so it is safe to re-run.
  All rows are imported as status='published'. Text is embedded with
  dollar-quoting ($md$...$md$) so single quotes need no escaping.

  NOTE: keep this script ASCII-only. Windows PowerShell reads .ps1 as
  ANSI, so non-ASCII literals here would break parsing. The .md/.html
  content is read with -Encoding UTF8 and is unaffected.
#>
[Console]::OutputEncoding=[System.Text.Encoding]::UTF8
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot   # temp-pages
$out  = Join-Path $root "supabase/migrations/0003_seed_articles.sql"

function Strip-Tags([string]$s) {
  if (-not $s) { return "" }
  $s = [regex]::Replace($s, '<br\s*/?>', ' ')
  $s = [regex]::Replace($s, '<[^>]+>', '')
  $s = [regex]::Replace($s, '\s+', ' ')
  return $s.Trim()
}

function Parse-Cards([string]$htmlPath, [string]$section) {
  $map = @{}
  if (-not (Test-Path $htmlPath)) { return $map }
  $html = Get-Content -Raw -Encoding UTF8 $htmlPath
  $blocks = [regex]::Matches($html, '<article class="note-item"[\s\S]*?</article>')
  foreach ($blk in $blocks) {
    $b = $blk.Value
    $cat   = ([regex]::Match($b, 'data-category="([^"]*)"').Groups[1].Value)
    $up    = ([regex]::Match($b, 'data-upload="([^"]*)"').Groups[1].Value)
    $ed    = ([regex]::Match($b, 'data-edit="([^"]*)"').Groups[1].Value)
    $title = ([regex]::Match($b, 'data-title="([^"]*)"').Groups[1].Value)
    $link  = [regex]::Match($b, 'note\.html\?(lit|file)=([^"&]+)')
    if (-not $link.Success) { continue }
    $slug  = [uri]::UnescapeDataString($link.Groups[2].Value)
    $pdfM  = [regex]::Match($b, 'note\.html\?pdf=([^"&]+)')
    $pdf   = if ($pdfM.Success) { "pdfs/" + [uri]::UnescapeDataString($pdfM.Groups[1].Value) + ".pdf" } else { $null }
    $imgs  = @()
    foreach ($im in [regex]::Matches($b, '<img[^>]*src="([^"]+)"')) {
      $src = $im.Groups[1].Value
      if ($src -like 'images/*') { $imgs += $src }
    }
    $cover = if ($imgs.Count) { $imgs[0] } else { $null }
    $extra = @()
    if ($imgs.Count -gt 1) { $extra = $imgs[1..($imgs.Count-1)] | ForEach-Object { @{ src = $_; caption = "" } } }
    $pM = [regex]::Match($b, '<p[^>]*>([\s\S]*?)</p>')
    $summary = if ($pM.Success) { Strip-Tags $pM.Groups[1].Value } else { "" }
    $map[$slug] = @{
      section=$section; slug=$slug; category=$cat; upload=$up; edit=$ed;
      title=$title; cover=$cover; images=$extra; pdf=$pdf; summary=$summary
    }
  }
  return $map
}

function Dq([string]$s) {
  if ($null -eq $s) { return "null" }
  return '$md$' + $s + '$md$'
}
function Ts([string]$d) {
  if ([string]::IsNullOrWhiteSpace($d)) { return "null" }
  return "'" + $d + "T00:00:00Z'::timestamptz"
}

$litCards  = Parse-Cards (Join-Path $root "literature.html") "literature"
$noteCards = Parse-Cards (Join-Path $root "directory.html")  "notes"

$rows = @()
foreach ($pair in @(@("literature",$litCards), @("notes",$noteCards))) {
  $section = $pair[0]; $cards = $pair[1]
  $dir = Join-Path $root $section
  if (-not (Test-Path $dir)) { continue }
  foreach ($f in Get-ChildItem -Path $dir -Filter *.md) {
    $slug = [System.IO.Path]::GetFileNameWithoutExtension($f.Name)
    $body = Get-Content -Raw -Encoding UTF8 $f.FullName
    $meta = $cards[$slug]
    $title = if ($meta -and $meta.title) { $meta.title } else {
      $h1 = [regex]::Match($body, '(?m)^#\s+(.+)$'); if ($h1.Success) { $h1.Groups[1].Value.Trim() } else { $slug }
    }
    $imagesJson = if ($meta -and $meta.images.Count) { ($meta.images | ConvertTo-Json -Compress -Depth 4) } else { "[]" }
    if ($imagesJson -notmatch '^\[') { $imagesJson = "[$imagesJson]" }
    $rows += [pscustomobject]@{
      section=$section; slug=$slug; title=$title;
      summary= if ($meta) { $meta.summary } else { "" };
      body=$body;
      cover= if ($meta) { $meta.cover } else { $null };
      images=$imagesJson;
      category= if ($meta) { $meta.category } else { $null };
      pdf= if ($meta) { $meta.pdf } else { $null };
      upload= if ($meta) { $meta.upload } else { $null };
      edit= if ($meta) { $meta.edit } else { $null };
    }
  }
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("-- 0003_seed_articles.sql (generated by tools/gen_seed_sql.ps1)")
[void]$sb.AppendLine("-- Imports existing literature/notes Markdown. Upserts on (section,slug); safe to re-run.")
[void]$sb.AppendLine("-- Run in Supabase SQL Editor AFTER 0001/0002.")
[void]$sb.AppendLine("")
foreach ($r in $rows) {
  $cover = if ($r.cover) { Dq $r.cover } else { "null" }
  $cat   = if ($r.category) { Dq $r.category } else { "null" }
  $pdf   = if ($r.pdf) { Dq $r.pdf } else { "null" }
  $imgLit = '$j$' + $r.images + '$j$::jsonb'
  [void]$sb.AppendLine("insert into public.articles (section, slug, title, summary, body, cover, images, category, tags, pdf_url, status, sort_index, published_at, created_at, updated_at) values (")
  [void]$sb.AppendLine("  $(Dq $r.section), $(Dq $r.slug), $(Dq $r.title), $(Dq $r.summary),")
  [void]$sb.AppendLine("  $(Dq $r.body),")
  [void]$sb.AppendLine("  $cover, $imgLit, $cat, '{}'::text[], $pdf, 'published', 0,")
  [void]$sb.AppendLine("  $(Ts $r.upload), $(Ts $r.upload), $(Ts $r.edit)")
  [void]$sb.AppendLine(") on conflict (section, slug) do update set")
  [void]$sb.AppendLine("  title=excluded.title, summary=excluded.summary, body=excluded.body, cover=excluded.cover,")
  [void]$sb.AppendLine("  images=excluded.images, category=excluded.category, pdf_url=excluded.pdf_url,")
  [void]$sb.AppendLine("  status=excluded.status, updated_at=excluded.updated_at;")
  [void]$sb.AppendLine("")
}

[System.IO.File]::WriteAllText($out, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Generated: $out"
Write-Host ("Articles: {0}" -f $rows.Count)
